### ISSUE TITLE
handle card not founds

### ISSUE THREAD

**Issue by jordanegiuly** [CoorpAcademy/trellit#121]

**Comment by jordanegiuly** [comment]
```
» 23 Oct 2015 14:50:50.333 2015-10-23 12:50:49.759947+00:00 app web.1 - - Unhandled rejection Error: invalid id at Request._callback (/app/node_modules/node-trello/lib/node-trello.js:88:13) at Request.self.callback (/app/node_modules/node-trello/node_modules/request/request.js:373:22) at emitTwo (events.js:87:13) at Request.emit (events.js:172:7) at Request.<anonymous> (/app/node_modules/node-trello/node_modules/request/request.js:1318:14) at emitOne (events.js:82:20) at Request.emit (events.js:169:7) at IncomingMessage.<anonymous> (/app/node_modules/node-trello/node_modules/request/request.js:1266:12) at emitNone (events.js:72:20) at IncomingMessage.emit (events.js:166:7) at endReadableNT (_stream_readable.js:903:12) at doNTCallback2 (node.js:439:9) at process._tickCallback (node.js:353:17) Exception Context
```

**Comment by jordanegiuly** [comment]
test

**Comment by jordanegiuly** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;c68olUjt&#x2F;598-121-handle-card-not-founds"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #121 - handle card not founds</a>
